# Generated by Django 6.0.7 on 2026-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField(help_text='Data do evento')),
                ('data_fim', models.DateField(blank=True, help_text='Data de término (se for um evento com duração)', null=True)),
                ('link_interativo', models.URLField(blank=True, help_text='Link pra mais informações (ex: Zoom, formulário, etc.)')),
                ('ativo', models.BooleanField(default=True, help_text='Eventos inativos não aparecem no calendário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data'],
            },
        ),
    ]
