# Generated by Django 6.0.7 on 2026-07-23 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do trabalho')),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, help_text='Quantidade de horas (ex: 8.5)', max_digits=5)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do trabalho realizado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='Funcionário', on_delete=django.db.models.deletion.CASCADE, related_name='registros_horas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Horas',
                'verbose_name_plural': 'Registros de Horas',
                'ordering': ['-data'],
            },
        ),
    ]
