# Generated by Django 6.0.7 on 2026-07-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor em reais', max_digits=8)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('confirmado', 'Confirmado'), ('falhou', 'Falhou'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20)),
                ('stripe_payment_id', models.CharField(blank=True, help_text='ID da transação no Stripe', max_length=255, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.OneToOneField(help_text='Agendamento que este pagamento está vinculado', on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='booking.agendamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
