# Generated by Django 6.0.7 on 2026-07-23 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do horário')),
                ('hora_inicio', models.TimeField(help_text='Hora de início (ex: 10:00)')),
                ('hora_fim', models.TimeField(help_text='Hora de término (ex: 11:00)')),
                ('servico', models.ForeignKey(help_text='Qual serviço é oferecido neste horário', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponiveis', to='services.servico')),
            ],
            options={
                'verbose_name': 'Horário Disponível',
                'verbose_name_plural': 'Horários Disponíveis',
                'ordering': ['data', 'hora_inicio'],
                'unique_together': {('servico', 'data', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(help_text='Cliente que fez o agendamento', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
                ('horario_disponivel', models.ForeignKey(help_text='Horário que foi reservado', on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='booking.horariodisponivel')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
